
server:
  port: 8080


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/db_project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_project
    password: 1234

  thymeleaf:
    cache: false


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update